which-oai-info: "{!ENV: MERRITT_OAI_INFO !DEFAULT: oai-info}"
  
oai-info:
  service:
    repositoryName: Merritt
    baseURL: "{!SSM: oai/config/baseURL !DEFAULT: http://merritt.cdlib.org/oai/v2}"
    protocolVersion: "2.0"
    adminEmail: "{!SSM: oai/config/adminEmail !DEFAULT: uc3@ucop.edu}"
    earliestDate: "{!SSM: oai/config/earliestDate !DEFAULT: 2013-05-22 09:47:24}"
    granularity: YYYY-MM-DDThh:mm:ssZ
    deletedMethod: "NO"
    maxListIdentifiers: "{!SSM: oai/config/maxListIdentifiers !DEFAULT: 10000}"
    maxListRecords: "{!SSM: oai/config/maxListRecords !DEFAULT: 10000}"
    maxListSets: "{!SSM: oai/config/maxListSets !DEFAULT: 100}"
    name: UC3
    identifier: "{!SSM: oai/config/identifier !DEFAULT: uc3-mrtoai-stg.cdlib.org}"

  fileLogger:
    messageMaximumLevel: "{!SSM: oai/config/log/messageMaximumLevel !DEFAULT: 5}"
    messageMaximumError: "{!SSM: oai/config/log/messageMaximumError !DEFAULT: 10}"
    path: "{!ENV: LOG_OAI !DEFAULT: /dpr2/mrtHomes/oaiHome}"
    name: oai
    qualifier: yyMMdd
    trace: 5
    
  db:
    user: "{!SSM: inv/readwrite/db-user}"
    password: "{!SSM: inv/readwrite/db-password}"
    host: "{!SSM: inv/db-host}"
    name: "{!SSM: inv/db-name}"
    encoding: "{!SSM: inv/db-encoding !DEFAULT: useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8}"

oai-info-docker: &docker
  service:
    repositoryName: Merritt
    baseURL: http://${HOSTNAME}.cdlib.org:8083/oai/v2
    protocolVersion: "2.0"
    adminEmail: uc3@ucop.edu
    earliestDate: 2013-05-22 09:47:24
    granularity: YYYY-MM-DDThh:mm:ssZ
    deletedMethod: "NO"
    maxListIdentifiers: "10000"
    maxListRecords: "10000"
    maxListSets: "100"
    name: UC3
    identifier: "{!ENV: ID_OAI !DEFAULT: mrtoai-docker}"
    threadPool: "5"
    queueCapacity: "15"
    nodePath: yaml
    replicQualify: NONE

  fileLogger:
    messageMaximumLevel: 5
    messageMaximumError: 10
    path: /tmp
    name: inv
    qualifier: yyMMdd
    trace: 5

  db:
    adapter: mysql2
    host: db-container
    name: db-name
    user: user
    password: password
    encoding: "characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&serverTimezone=UTC"   # schema won't load if it's utf8mb4
